# This is the base config file for mise.
# It includes the main [settings] and [tools] sections.

[settings]
experimental = true

[tools]
neovim = "latest"
node = "20"
zoxide = "latest"
fzf = "latest"
fd = "latest"
ripgrep = "latest"
bat = "latest"
eza = "latest"
delta = "latest"
python = "3.11"
choose = "latest"